// MiniRedmine.Web/FrontEnd/src/pages/Login.svelte
<script>
  import axios from "axios";
  import StorageService from "../services/StorageService";

  export let handleNavigation;

  async function handleSubmit(event) {
    event.preventDefault();
    const res = await fetch(`api/redmine/userinfo?userApiKey=${userApiKey}`);
    StorageService.storeUser(await res.json())
    handleNavigation(null, "/");
  }
  let userApiKey = null;
</script>

<div class="container">
  <div class="row">
    <div class="col">
      <form on:submit={handleSubmit}>
        <h1 class="h3 mb-3 font-weight-normal">
          Please input your Redmine Api Key
        </h1>
        <label for="inputApiKey" class="sr-only">Api Key</label>
        <input
          type="text"
          id="inputApiKey"
          class="form-control"
          placeholder="Redmine Api Key"
          required=""
          bind:value={userApiKey} />
        <button class="btn btn-lg btn-primary btn-block" type="submit">
          Login
        </button>
      </form>
    </div>
  </div>
</div>

// MiniRedmine.Web/FrontEnd/src/components/Login.jsx
﻿import axios from 'axios';
import React, { useState } from 'react';
import { useHistory, useLocation } from 'react-router-dom';
import Button from 'react-bootstrap/Button';
import Col from 'react-bootstrap/Col';
import Form from 'react-bootstrap/Form';
import InputGroup from 'react-bootstrap/InputGroup';
import Container from 'react-bootstrap/Container';
import UserInfoService from '../services/UserInfoService';

function Login() {
    const [userApiToken, setUserApiToken] = useState(UserInfoService.getApiKey());
    let history = useHistory();
    let location = useLocation();
    let { from } = location.state || { from: { pathname: "/" } };    
    const loginCallBack = () => history.replace(from);   

    async function loginUser(event) {
        event.preventDefault();
        if (userApiToken !== '') {
            let userResponse = await axios.get(`api/redmine/userinfo?userApiKey=${userApiToken}`);
            let activitiesResponse = await axios.get(`api/redmine/timeentryactivities?userApiKey=${userApiToken}`);            
            UserInfoService.signIn(userApiToken, userResponse.data, activitiesResponse.data);
            loginCallBack();
        }
    }

    return (
        <Container fluid="true">
            <Form onSubmit={loginUser}>
                <Form.Row>
                    <Form.Group as={Col}>
                        <InputGroup>
                            <Form.Control type="text" placeholder="Redmine Api Token" value={userApiToken} onChange={e => setUserApiToken(e.target.value)} />
                            <InputGroup.Append>
                                <Button variant="primary" type="submit">Login</Button>
                            </InputGroup.Append>
                        </InputGroup>
                    </Form.Group>
                </Form.Row>
            </Form>
        </Container>
    );
}

export default Login;
