// MiniRedmine.Web/FrontEnd/src/components/Header.svelte
﻿<script>
  export let handleNavigation;
  import { user } from "../stores/userstore";
</script>

<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-3">
  <a class="navbar-brand" href="/" on:click={(e) => handleNavigation(e, '/')}>
    Mini Redmine 2
  </a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#mainnavbar"
    aria-controls="mainnavbar"
    aria-expanded="false"
    aria-label="Toggle navigation">
    <span class="navbar-toggler-icon" />
  </button>
  <div class="collapse navbar-collapse" id="mainnavbar">
    <ul class="navbar-nav mr-auto">
      {#if $user.unauthorized === true}
        <li class="nav-item">
          <a
            class="nav-link"
            href="/login"
            on:click={(e) => handleNavigation(e, '/login')}>
            Login
          </a>
        </li>
      {:else}
        <li class="nav-item">
          <a
            class="nav-link"
            href="/profile"
            on:click={(e) => handleNavigation(e, '/profile')}>
            Profile
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="/issues"
            on:click={(e) => handleNavigation(e, '/issues')}>
            Issues
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="/templates"
            on:click={(e) => handleNavigation(e, '/templates')}>
            Templates
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="/timeentries"
            on:click={(e) => handleNavigation(e, '/timeentries')}>
            Time Entries
          </a>
        </li>
      {/if}
    </ul>
  </div>
</nav>

// MiniRedmine.Web/src/miniredmine/components/Header.jsx
import React from 'react';
import { Link, NavLink } from 'react-router-dom';

// The Header creates links that can be used to navigate
// between routes.
const Header = () => (
  <header>
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark">
      <Link className="navbar-brand" to={{pathname: '/', state:{fromMenu:true}}}>
        Mini Redmine
      </Link>
      <button
        className="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarMain"
        aria-controls="navbarColor01"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span className="navbar-toggler-icon" />
      </button>

      <div className="collapse navbar-collapse" id="navbarMain">
        <ul className="navbar-nav mr-auto">
          <li className="nav-item">
            <NavLink activeClassName="active" className="nav-link" to={{pathname: '/', state:{fromMenu:true}}}>
              Home
            </NavLink>
          </li>
          <li className="nav-item">
            <NavLink activeClassName="active" className="nav-link" to="/timeentries">
              TimeEntries
            </NavLink>
          </li>
        </ul>
      </div>
    </nav>
  </header>
);

export default Header;
