// MiniRedmine.Web/frontend-react/src/app/pages/Login/index.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router';
import { useUser } from '../../providers/User';

export function LoginPage() {
  const { setUser } = useUser(); // Update user context
  const [apiKey, setApiKey] = useState('');
  const navigate = useNavigate(); // For navigation

  const handleSubmit = async (event) => {
    event.preventDefault();
    try {
      const res = await fetch('/api/redmine/userinfo', {
        headers: {
          'Redmine-Key': `${apiKey}`,
        },
      });

      if (res.ok) {
        const userInfo = await res.json();
        setUser({ ...userInfo, isAuthenticated: true }); // Update context
        localStorage.setItem('REDMINE_USER', JSON.stringify(userInfo)); // Persist user
        navigate('/'); // Navigate to home
      } else {
        console.error('Failed to login: ', res.statusText);
      }
    } catch (error) {
      console.error('Error during login:', error);
    }
  };

  return (
    <div className="row">
      <div className="col">
        <h1>Login</h1>
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="apikey">Redmine API Key</label>
            <input
              type="text"
              className="form-control"
              id="apikey"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              required
            />
          </div>
          <button type="submit" className="btn btn-primary">
            Login
          </button>
        </form>
      </div>
    </div>
  );
}

// MiniRedmine.Web/FrontEnd/src/pages/Login.svelte
<script lang="ts">
  import { user } from "../stores/userstore";

  export let handleNavigation:Function;

  async function handleSubmit(event:Event):Promise<void> {
    event.preventDefault();
    const res = await fetch('/api/redmine/userinfo',{
      headers:{
        'Redmine-Key':`${userApiKey}`
      }
    });
    user.register(await res.json());
    handleNavigation(null, "/");
  }
  let userApiKey: string;
</script>

<div class="container">
  <div class="row">
    <div class="col">
      <form on:submit={handleSubmit}>
        <h1 class="h3 mb-3 font-weight-normal">
          Please input your Redmine Api Key
        </h1>
        <label for="inputApiKey" class="sr-only">Api Key</label>
        <input
          type="text"
          id="inputApiKey"
          class="form-control"
          placeholder="Redmine Api Key"
          required
          bind:value={userApiKey} />
        <button class="btn btn-lg btn-primary btn-block" type="submit">
          Login
        </button>
      </form>
    </div>
  </div>
</div>
